import type { Metadata } from "next";
import "./globals.css";

// ─── Change this to your real production domain once deployed ───────────────
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://rakshshrestha.com.np";

export const metadata: Metadata = {
  // ── Basic ──────────────────────────────────────────────────────────────────
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Rakesh Shrestha — UI/UX Designer & Product Designer | Kathmandu, Nepal",
    template: "%s | Rakesh Shrestha",
  },
  description:
    "Rakesh Shrestha is a UI/UX Designer and Product Designer based in Kathmandu, Nepal. Specialising in Figma, user-centered design, edtech, and frontend development. 2× hackathon runner-up.",
  keywords: [
    "web designer graphic heavy ui creative kathmandu",
    "ui ux designer modern brutalism freelance kathmandu",
    "user experience designer neo brutalism best design remote",
    "product designer brutalist ui website asia",
    "web designer neobrutalist best design nepal",
    "user experience designer bold ui website remote",
    "mobile app designer bold ui creative remote",
    "product designer neo brutalism website kathmandu",
    "user interface designer bold ui award winning asia",
    "user interface designer graphic heavy ui freelance nepal",
    "product designer modern brutalism minimal kathmandu",
    "user experience designer neobrutalist portfolio asia",
    "product designer graphic heavy ui modern global",
    "mobile app designer neobrutalist case study remote",
    "user experience designer experimental ui website nepal",
    "web designer experimental ui minimal kathmandu",
    "user interface designer bold ui minimal global",
    "product designer brutalist ui case study remote",
    "product designer neobrutalist best design kathmandu",
    "mobile app designer bold ui modern asia",
    "mobile app designer experimental ui case study asia",
    "web designer modern brutalism website global",
    "ui ux designer graphic heavy ui case study nepal",
    "digital designer neobrutalist portfolio nepal",
    "user experience designer brutalist ui portfolio nepal",
    "mobile app designer experimental ui freelance remote",
    "user interface designer brutalist ui award winning asia",
    "web designer brutalist ui website remote",
    "user interface designer bold ui professional global",
    "product designer modern brutalism modern asia",
    "product designer brutalist ui freelance kathmandu",
    "user interface designer graphic heavy ui modern remote",
    "user interface designer bold ui creative remote",
    "web designer modern brutalism award winning kathmandu",
    "user experience designer modern brutalism modern global",
    "user experience designer graphic heavy ui freelance remote",
    "product designer experimental ui website remote",
    "user interface designer brutalist ui portfolio asia",
    "mobile app designer graphic heavy ui award winning kathmandu",
    "digital designer neo brutalism professional nepal",
    "product designer graphic heavy ui best design asia",
    "web designer modern brutalism case study remote",
    "digital designer brutalist ui best design kathmandu",
    "ui ux designer experimental ui creative asia",
    "web designer neobrutalist modern kathmandu",
    "product designer experimental ui freelance kathmandu",
    "ui ux designer brutalist ui modern kathmandu",
    "product designer experimental ui modern remote",
    "digital designer bold ui minimal nepal",
    "product designer bold ui creative kathmandu",
    "digital designer experimental ui creative kathmandu",
    "user experience designer graphic heavy ui professional asia",
    "ui ux designer modern brutalism modern remote",
    "ui ux designer neobrutalist professional nepal",
    "product designer brutalist ui freelance nepal",
    "product designer neo brutalism award winning global",
    "ui ux designer graphic heavy ui portfolio asia",
    "user experience designer brutalist ui website global",
    "mobile app designer modern brutalism freelance remote",
    "mobile app designer bold ui best design global",
    "user experience designer modern brutalism best design kathmandu",
    "product designer brutalist ui portfolio kathmandu",
    "user experience designer neobrutalist minimal remote",
    "mobile app designer neo brutalism case study global",
    "user interface designer neobrutalist website asia",
    "user interface designer brutalist ui website nepal",
    "product designer neobrutalist minimal asia",
    "mobile app designer bold ui case study remote",
    "mobile app designer bold ui portfolio kathmandu",
    "ui ux designer brutalist ui minimal remote",
    "web designer neo brutalism portfolio global",
    "user interface designer neo brutalism portfolio kathmandu",
    "digital designer neobrutalist modern remote",
    "digital designer brutalist ui minimal global",
    "web designer bold ui professional kathmandu",
    "mobile app designer experimental ui website nepal",
    "product designer experimental ui award winning remote",
    "digital designer brutalist ui modern remote",
    "user experience designer modern brutalism minimal global",
    "digital designer brutalist ui award winning remote",
    "web designer modern brutalism freelance kathmandu",
    "mobile app designer experimental ui creative nepal",
    "user interface designer graphic heavy ui minimal asia",
    "user interface designer bold ui case study kathmandu",
    "ui ux designer bold ui minimal asia",
    "user interface designer experimental ui case study remote",
    "mobile app designer modern brutalism modern remote",
    "mobile app designer neobrutalist portfolio asia",
    "digital designer bold ui award winning asia",
    "product designer bold ui modern global",
    "product designer modern brutalism portfolio remote",
    "ui ux designer bold ui freelance asia",
    "user experience designer neobrutalist award winning remote",
    "digital designer brutalist ui minimal kathmandu",
    "mobile app designer neobrutalist minimal asia",
    "web designer graphic heavy ui best design asia",
    "user experience designer neobrutalist portfolio remote",
    "digital designer neo brutalism website nepal",
    "digital designer brutalist ui award winning nepal",
    "product designer neo brutalism portfolio kathmandu",
    "digital designer neobrutalist freelance asia",
    "digital designer experimental ui professional kathmandu",
    "mobile app designer neobrutalist portfolio nepal",
    "user interface designer modern brutalism portfolio nepal",
    "digital designer neobrutalist best design global",
    "mobile app designer experimental ui creative asia",
    "product designer neo brutalism award winning kathmandu",
    "mobile app designer neo brutalism portfolio remote",
    "digital designer bold ui freelance asia",
    "digital designer neobrutalist best design kathmandu",
    "digital designer bold ui minimal global",
    "mobile app designer neo brutalism freelance kathmandu",
    "digital designer bold ui portfolio nepal",
    "user experience designer brutalist ui award winning global",
    "web designer neobrutalist website remote",
    "user experience designer brutalist ui portfolio asia",
    "product designer experimental ui best design remote",
    "mobile app designer neo brutalism portfolio asia",
    "digital designer neo brutalism website remote",
    "ui ux designer neo brutalism best design asia",
    "mobile app designer neobrutalist freelance asia",
    "user experience designer neobrutalist modern global",
    "product designer bold ui professional remote",
    "web designer bold ui modern nepal",
    "mobile app designer neo brutalism case study kathmandu",
    "digital designer modern brutalism minimal asia",
    "user experience designer neo brutalism portfolio kathmandu",
    "web designer neo brutalism modern asia",
    "product designer bold ui portfolio kathmandu",
    "user experience designer brutalist ui website nepal",
    "user experience designer experimental ui website asia",
    "web designer brutalist ui best design nepal",
    "mobile app designer experimental ui modern global",
    "ui ux designer neobrutalist website nepal",
    "user interface designer modern brutalism modern asia",
    "product designer modern brutalism website asia",
    "mobile app designer experimental ui professional global",
    "product designer graphic heavy ui creative nepal",
    "user experience designer neo brutalism creative asia",
    "ui ux designer modern brutalism best design global",
    "digital designer brutalist ui creative remote",
    "ui ux designer neo brutalism creative asia",
    "web designer experimental ui modern kathmandu",
    "mobile app designer graphic heavy ui portfolio global",
    "user interface designer neobrutalist portfolio asia",
    "user interface designer neobrutalist freelance asia",
    "user interface designer modern brutalism freelance remote",
    "digital designer bold ui professional kathmandu",
    "ui ux designer modern brutalism award winning asia",
    "user experience designer neo brutalism website global",
    "user interface designer bold ui minimal remote",
    "product designer neobrutalist website nepal",
    "web designer graphic heavy ui case study asia",
    "user interface designer graphic heavy ui creative global",
    "ui ux designer bold ui minimal asia",
    "user interface designer experimental ui case study remote",
    "mobile app designer modern brutalism modern remote",
    "mobile app designer neobrutalist portfolio asia",
    "digital designer bold ui award winning asia",
    "product designer bold ui modern global",
    "product designer modern brutalism portfolio remote",
    "ui ux designer bold ui freelance asia",
    "user experience designer neobrutalist award winning remote",
    "digital designer brutalist ui minimal kathmandu",
    "mobile app designer neobrutalist minimal asia",
    "web designer graphic heavy ui best design asia",
    "user experience designer neobrutalist portfolio remote",
    "digital designer neo brutalism website nepal",
    "digital designer brutalist ui award winning nepal",
    "product designer neo brutalism portfolio kathmandu",
    "digital designer neobrutalist freelance asia",
    "digital designer experimental ui professional kathmandu",
    "mobile app designer neobrutalist portfolio nepal",
    "user interface designer modern brutalism portfolio nepal",
    "digital designer neobrutalist best design global",
    "mobile app designer experimental ui creative asia",
    "product designer neo brutalism award winning kathmandu",
    "mobile app designer neo brutalism portfolio remote",
    "digital designer bold ui freelance asia",
    "digital designer neobrutalist best design kathmandu",
    "digital designer bold ui minimal global",
    "mobile app designer neo brutalism freelance kathmandu",
    "digital designer bold ui portfolio nepal",
    "user experience designer brutalist ui award winning global",
    "web designer neobrutalist website remote",
    "user experience designer brutalist ui portfolio asia",
    "product designer experimental ui best design remote",
    "mobile app designer neo brutalism portfolio asia",
    "digital designer neo brutalism website remote",
    "ui ux designer neo brutalism best design asia",
    "mobile app designer neobrutalist freelance asia",
    "user experience designer neobrutalist modern global",
    "product designer bold ui professional remote",
    "web designer bold ui modern nepal",
    "mobile app designer neo brutalism case study kathmandu",
    "digital designer modern brutalism minimal asia",
    "user experience designer neo brutalism portfolio kathmandu",
    "web designer neo brutalism modern asia",
    "product designer bold ui portfolio kathmandu",
    "user experience designer brutalist ui website nepal",
    "user experience designer experimental ui website asia",
    "web designer brutalist ui best design nepal",
    "mobile app designer experimental ui modern global",
    "ui ux designer neobrutalist website nepal",
    "user interface designer modern brutalism modern asia",
    "product designer modern brutalism website asia",
    "mobile app designer experimental ui professional global",
    "product designer graphic heavy ui creative nepal",
    "user experience designer neo brutalism creative asia",
    "ui ux designer modern brutalism best design global",
    "digital designer brutalist ui creative remote",
    "ui ux designer neo brutalism creative asia",
    "web designer experimental ui modern kathmandu",
    "mobile app designer graphic heavy ui portfolio global",
    "user interface designer neobrutalist portfolio asia",
    "user interface designer neobrutalist freelance asia",
    "user interface designer modern brutalism freelance remote",
    "digital designer bold ui professional kathmandu",
    "ui ux designer modern brutalism award winning asia",
    "user experience designer neo brutalism website global",
    "user interface designer bold ui minimal remote",
    "product designer neobrutalist website nepal",
    "web designer graphic heavy ui case study asia",
    "user interface designer graphic heavy ui creative global",
    "ui ux designer bold ui minimal asia",
    "user interface designer experimental ui case study remote",
    "mobile app designer modern brutalism modern remote",
    "Rakesh Shrestha",
    "Rakesh Shrestha designer",
    "Rakesh Shrestha portfolio",
    "UI UX designer Kathmandu",
    "product designer Nepal",
    "UX designer Kathmandu",
    "web designer Kathmandu",
    "mobile app designer Nepal",
    "digital designer Nepal",
    "user experience designer Nepal",
    "user interface designer Kathmandu",
    "freelance UI UX designer Nepal",
    "freelance product designer Kathmandu",
    "neobrutalist UI designer",
    "brutalist UI designer Nepal",
    "neo brutalism product designer",
    "bold UI designer Kathmandu",
    "graphic heavy UI designer",
    "modern brutalism designer Nepal",
    "experimental UI designer",
    "Figma designer Nepal",
    "Figma expert Kathmandu",
    "edtech designer Nepal",
    "frontend designer Nepal",
    "UI UX designer Asia",
    "product designer Asia",
    "remote UI UX designer",
    "award winning designer Nepal",
    "portfolio Nepal",
  ],
  authors: [{ name: "Rakesh Shrestha", url: SITE_URL }],
  creator: "Rakesh Shrestha",
  publisher: "Rakesh Shrestha",

  // ── Canonical + robots ─────────────────────────────────────────────────────
  // metadataBase handles absolute URL resolution for all relative paths below.
  // The canonical is set per-page via alternates; the global fallback is the root.
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // ── Open Graph ─────────────────────────────────────────────────────────────
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Rakesh Shrestha Portfolio",
    title: "Rakesh Shrestha — UI/UX Designer & Product Designer | Kathmandu, Nepal",
    description:
      "UI/UX Designer and Product Designer based in Kathmandu, Nepal. Figma expert, 2× hackathon runner-up, passionate about edtech and user-centered design.",
    images: [
      {
        url: "/og.png",          // place a 1200×630 image at public/og.png
        width: 1200,
        height: 630,
        alt: "Rakesh Shrestha — UI/UX Designer Portfolio",
      },
    ],
  },

  // ── Twitter / X card ───────────────────────────────────────────────────────
  twitter: {
    card: "summary_large_image",
    title: "Rakesh Shrestha — UI/UX Designer & Product Designer",
    description:
      "UI/UX Designer based in Kathmandu, Nepal. Figma expert, 2× hackathon runner-up.",
    images: ["/og.png"],
    // creator: "@yourhandle",   // add if you have a Twitter/X account
  },

  // ── Icons ──────────────────────────────────────────────────────────────────
  icons: {
    icon: [
      { url: "/favicon.png", type: "image/png" },
    ],
    apple: "/favicon.png",
  },

  // ── Verification (fill in after Search Console setup) ─────────────────────
  verification: {
    google: [
      process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION ?? "",
      process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION_2 ?? "",
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
