import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

// ─── Change this to your real production domain once deployed ───────────────
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://rakeshshrestha.vercel.app";

export const metadata: Metadata = {
  // ── Basic ──────────────────────────────────────────────────────────────────
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Rakesh Shrestha — UI/UX Designer & Product Designer | Kathmandu, Nepal",
    template: "%s | Rakesh Shrestha",
  },
  description:
    "UI/UX & Product Designer in Kathmandu, Nepal. Figma expert, neobrutalist design, edtech focus. 2× hackathon runner-up. Available for freelance.",
  keywords: [
    "web designer graphic heavy ui creative kathmandu",
    "ui ux designer modern brutalism freelance kathmandu",
    "user experience designer neo brutalism best design remote",
    "product designer brutalist ui website asia",
    "web designer neobrutalist best design nepal",
    "user experience designer bold ui website remote",
    "mobile app designer bold ui creative remote",
    "product designer neo brutalism website kathmandu",
    "user interface designer bold ui award winning asia",
    "user interface designer graphic heavy ui freelance nepal",
    "product designer modern brutalism minimal kathmandu",
    "user experience designer neobrutalist portfolio asia",
    "product designer graphic heavy ui modern global",
    "mobile app designer neobrutalist case study remote",
    "user experience designer experimental ui website nepal",
    "web designer experimental ui minimal kathmandu",
    "user interface designer bold ui minimal global",
    "product designer brutalist ui case study remote",
    "product designer neobrutalist best design kathmandu",
    "mobile app designer bold ui modern asia",
    "mobile app designer experimental ui case study asia",
    "web designer modern brutalism website global",
    "ui ux designer graphic heavy ui case study nepal",
    "digital designer neobrutalist portfolio nepal",
    "user experience designer brutalist ui portfolio nepal",
    "mobile app designer experimental ui freelance remote",
    "user interface designer brutalist ui award winning asia",
    "web designer brutalist ui website remote",
    "user interface designer bold ui professional global",
    "product designer modern brutalism modern asia",
    "product designer brutalist ui freelance kathmandu",
    "user interface designer graphic heavy ui modern remote",
    "user interface designer bold ui creative remote",
    "web designer modern brutalism award winning kathmandu",
    "user experience designer modern brutalism modern global",
    "user experience designer graphic heavy ui freelance remote",
    "product designer experimental ui website remote",
    "user interface designer brutalist ui portfolio asia",
    "mobile app designer graphic heavy ui award winning kathmandu",
    "digital designer neo brutalism professional nepal",
    "product designer graphic heavy ui best design asia",
    "web designer modern brutalism case study remote",
    "digital designer brutalist ui best design kathmandu",
    "ui ux designer experimental ui creative asia",
    "web designer neobrutalist modern kathmandu",
    "product designer experimental ui freelance kathmandu",
    "ui ux designer brutalist ui modern kathmandu",
    "product designer experimental ui modern remote",
    "digital designer bold ui minimal nepal",
    "product designer bold ui creative kathmandu",
    "digital designer experimental ui creative kathmandu",
    "user experience designer graphic heavy ui professional asia",
    "ui ux designer modern brutalism modern remote",
    "ui ux designer neobrutalist professional nepal",
    "product designer brutalist ui freelance nepal",
    "product designer neo brutalism award winning global",
    "ui ux designer graphic heavy ui portfolio asia",
    "user experience designer brutalist ui website global",
    "mobile app designer modern brutalism freelance remote",
    "mobile app designer bold ui best design global",
    "user experience designer modern brutalism best design kathmandu",
    "product designer brutalist ui portfolio kathmandu",
    "user experience designer neobrutalist minimal remote",
    "mobile app designer neo brutalism case study global",
    "user interface designer neobrutalist website asia",
    "user interface designer brutalist ui website nepal",
    "product designer neobrutalist minimal asia",
    "mobile app designer bold ui case study remote",
    "mobile app designer bold ui portfolio kathmandu",
    "ui ux designer brutalist ui minimal remote",
    "web designer neo brutalism portfolio global",
    "user interface designer neo brutalism portfolio kathmandu",
    "digital designer neobrutalist modern remote",
    "digital designer brutalist ui minimal global",
    "web designer bold ui professional kathmandu",
    "mobile app designer experimental ui website nepal",
    "product designer experimental ui award winning remote",
    "digital designer brutalist ui modern remote",
    "user experience designer modern brutalism minimal global",
    "digital designer brutalist ui award winning remote",
    "web designer modern brutalism freelance kathmandu",
    "mobile app designer experimental ui creative nepal",
    "user interface designer graphic heavy ui minimal asia",
    "user interface designer bold ui case study kathmandu",
    "ui ux designer bold ui minimal asia",
    "user interface designer experimental ui case study remote",
    "mobile app designer modern brutalism modern remote",
    "mobile app designer neobrutalist portfolio asia",
    "digital designer bold ui award winning asia",
    "product designer bold ui modern global",
    "product designer modern brutalism portfolio remote",
    "ui ux designer bold ui freelance asia",
    "user experience designer neobrutalist award winning remote",
    "digital designer brutalist ui minimal kathmandu",
    "mobile app designer neobrutalist minimal asia",
    "web designer graphic heavy ui best design asia",
    "user experience designer neobrutalist portfolio remote",
    "digital designer neo brutalism website nepal",
    "digital designer brutalist ui award winning nepal",
    "product designer neo brutalism portfolio kathmandu",
    "digital designer neobrutalist freelance asia",
    "digital designer experimental ui professional kathmandu",
    "mobile app designer neobrutalist portfolio nepal",
    "user interface designer modern brutalism portfolio nepal",
    "digital designer neobrutalist best design global",
    "mobile app designer experimental ui creative asia",
    "product designer neo brutalism award winning kathmandu",
    "mobile app designer neo brutalism portfolio remote",
    "digital designer bold ui freelance asia",
    "digital designer neobrutalist best design kathmandu",
    "digital designer bold ui minimal global",
    "mobile app designer neo brutalism freelance kathmandu",
    "digital designer bold ui portfolio nepal",
    "user experience designer brutalist ui award winning global",
    "web designer neobrutalist website remote",
    "user experience designer brutalist ui portfolio asia",
    "product designer experimental ui best design remote",
    "mobile app designer neo brutalism portfolio asia",
    "digital designer neo brutalism website remote",
    "ui ux designer neo brutalism best design asia",
    "mobile app designer neobrutalist freelance asia",
    "user experience designer neobrutalist modern global",
    "product designer bold ui professional remote",
    "web designer bold ui modern nepal",
    "mobile app designer neo brutalism case study kathmandu",
    "digital designer modern brutalism minimal asia",
    "user experience designer neo brutalism portfolio kathmandu",
    "web designer neo brutalism modern asia",
    "product designer bold ui portfolio kathmandu",
    "user experience designer brutalist ui website nepal",
    "user experience designer experimental ui website asia",
    "web designer brutalist ui best design nepal",
    "mobile app designer experimental ui modern global",
    "ui ux designer neobrutalist website nepal",
    "user interface designer modern brutalism modern asia",
    "product designer modern brutalism website asia",
    "mobile app designer experimental ui professional global",
    "product designer graphic heavy ui creative nepal",
    "user experience designer neo brutalism creative asia",
    "ui ux designer modern brutalism best design global",
    "digital designer brutalist ui creative remote",
    "ui ux designer neo brutalism creative asia",
    "web designer experimental ui modern kathmandu",
    "mobile app designer graphic heavy ui portfolio global",
    "user interface designer neobrutalist portfolio asia",
    "user interface designer neobrutalist freelance asia",
    "user interface designer modern brutalism freelance remote",
    "digital designer bold ui professional kathmandu",
    "ui ux designer modern brutalism award winning asia",
    "user experience designer neo brutalism website global",
    "user interface designer bold ui minimal remote",
    "product designer neobrutalist website nepal",
    "web designer graphic heavy ui case study asia",
    "user interface designer graphic heavy ui creative global",
    "ui ux designer bold ui minimal asia",
    "user interface designer experimental ui case study remote",
    "mobile app designer modern brutalism modern remote",
    "mobile app designer neobrutalist portfolio asia",
    "digital designer bold ui award winning asia",
    "product designer bold ui modern global",
    "product designer modern brutalism portfolio remote",
    "ui ux designer bold ui freelance asia",
    "user experience designer neobrutalist award winning remote",
    "digital designer brutalist ui minimal kathmandu",
    "mobile app designer neobrutalist minimal asia",
    "web designer graphic heavy ui best design asia",
    "user experience designer neobrutalist portfolio remote",
    "digital designer neo brutalism website nepal",
    "digital designer brutalist ui award winning nepal",
    "product designer neo brutalism portfolio kathmandu",
    "digital designer neobrutalist freelance asia",
    "digital designer experimental ui professional kathmandu",
    "mobile app designer neobrutalist portfolio nepal",
    "user interface designer modern brutalism portfolio nepal",
    "digital designer neobrutalist best design global",
    "mobile app designer experimental ui creative asia",
    "product designer neo brutalism award winning kathmandu",
    "mobile app designer neo brutalism portfolio remote",
    "digital designer bold ui freelance asia",
    "digital designer neobrutalist best design kathmandu",
    "digital designer bold ui minimal global",
    "mobile app designer neo brutalism freelance kathmandu",
    "digital designer bold ui portfolio nepal",
    "user experience designer brutalist ui award winning global",
    "web designer neobrutalist website remote",
    "user experience designer brutalist ui portfolio asia",
    "product designer experimental ui best design remote",
    "mobile app designer neo brutalism portfolio asia",
    "digital designer neo brutalism website remote",
    "ui ux designer neo brutalism best design asia",
    "mobile app designer neobrutalist freelance asia",
    "user experience designer neobrutalist modern global",
    "product designer bold ui professional remote",
    "web designer bold ui modern nepal",
    "mobile app designer neo brutalism case study kathmandu",
    "digital designer modern brutalism minimal asia",
    "user experience designer neo brutalism portfolio kathmandu",
    "web designer neo brutalism modern asia",
    "product designer bold ui portfolio kathmandu",
    "user experience designer brutalist ui website nepal",
    "user experience designer experimental ui website asia",
    "web designer brutalist ui best design nepal",
    "mobile app designer experimental ui modern global",
    "ui ux designer neobrutalist website nepal",
    "user interface designer modern brutalism modern asia",
    "product designer modern brutalism website asia",
    "mobile app designer experimental ui professional global",
    "product designer graphic heavy ui creative nepal",
    "user experience designer neo brutalism creative asia",
    "ui ux designer modern brutalism best design global",
    "digital designer brutalist ui creative remote",
    "ui ux designer neo brutalism creative asia",
    "web designer experimental ui modern kathmandu",
    "mobile app designer graphic heavy ui portfolio global",
    "user interface designer neobrutalist portfolio asia",
    "user interface designer neobrutalist freelance asia",
    "user interface designer modern brutalism freelance remote",
    "digital designer bold ui professional kathmandu",
    "ui ux designer modern brutalism award winning asia",
    "user experience designer neo brutalism website global",
    "user interface designer bold ui minimal remote",
    "product designer neobrutalist website nepal",
    "web designer graphic heavy ui case study asia",
    "user interface designer graphic heavy ui creative global",
    "ui ux designer bold ui minimal asia",
    "user interface designer experimental ui case study remote",
    "mobile app designer modern brutalism modern remote",
    "Rakesh Shrestha",
    "Rakesh Shrestha designer",
    "Rakesh Shrestha portfolio",
    "UI UX designer Kathmandu",
    "product designer Nepal",
    "UX designer Kathmandu",
    "web designer Kathmandu",
    "mobile app designer Nepal",
    "digital designer Nepal",
    "user experience designer Nepal",
    "user interface designer Kathmandu",
    "freelance UI UX designer Nepal",
    "freelance product designer Kathmandu",
    "neobrutalist UI designer",
    "brutalist UI designer Nepal",
    "neo brutalism product designer",
    "bold UI designer Kathmandu",
    "graphic heavy UI designer",
    "modern brutalism designer Nepal",
    "experimental UI designer",
    "Figma designer Nepal",
    "Figma expert Kathmandu",
    "edtech designer Nepal",
    "frontend designer Nepal",
    "UI UX designer Asia",
    "product designer Asia",
    "remote UI UX designer",
    "award winning designer Nepal",
    "portfolio Nepal",
    // Branded — ui ux designer
    "Rakesh Shrestha ui ux designer neo brutalism portfolio nepal",
    "Rakesh Shrestha ui ux designer neo brutalism portfolio kathmandu",
    "Rakesh Shrestha ui ux designer neo brutalism portfolio asia",
    "Rakesh Shrestha ui ux designer neo brutalism portfolio remote",
    "Rakesh Shrestha ui ux designer neo brutalism portfolio global",
    "Rakesh Shrestha ui ux designer neobrutalist portfolio nepal",
    "Rakesh Shrestha ui ux designer neobrutalist portfolio kathmandu",
    "Rakesh Shrestha ui ux designer brutalist ui portfolio nepal",
    "Rakesh Shrestha ui ux designer brutalist ui portfolio kathmandu",
    "Rakesh Shrestha ui ux designer modern brutalism portfolio nepal",
    "Rakesh Shrestha ui ux designer modern brutalism portfolio kathmandu",
    "Rakesh Shrestha ui ux designer bold ui portfolio nepal",
    "Rakesh Shrestha ui ux designer bold ui portfolio kathmandu",
    "Rakesh Shrestha ui ux designer experimental ui portfolio nepal",
    "Rakesh Shrestha ui ux designer graphic heavy ui portfolio nepal",
    "Rakesh Shrestha ui ux designer neo brutalism website nepal",
    "Rakesh Shrestha ui ux designer neo brutalism website kathmandu",
    "Rakesh Shrestha ui ux designer neo brutalism case study nepal",
    "Rakesh Shrestha ui ux designer neo brutalism case study kathmandu",
    "Rakesh Shrestha ui ux designer neo brutalism best design nepal",
    "Rakesh Shrestha ui ux designer neo brutalism best design kathmandu",
    "Rakesh Shrestha ui ux designer neo brutalism creative nepal",
    "Rakesh Shrestha ui ux designer neo brutalism creative kathmandu",
    "Rakesh Shrestha ui ux designer neo brutalism modern nepal",
    "Rakesh Shrestha ui ux designer neo brutalism modern kathmandu",
    "Rakesh Shrestha ui ux designer neo brutalism professional nepal",
    "Rakesh Shrestha ui ux designer neo brutalism professional kathmandu",
    "Rakesh Shrestha ui ux designer neo brutalism freelance nepal",
    "Rakesh Shrestha ui ux designer neo brutalism freelance kathmandu",
    "Rakesh Shrestha ui ux designer neo brutalism hire nepal",
    "Rakesh Shrestha ui ux designer neo brutalism hire kathmandu",
    "Rakesh Shrestha ui ux designer neo brutalism award winning nepal",
    "Rakesh Shrestha ui ux designer neo brutalism award winning kathmandu",
    "Rakesh Shrestha ui ux designer neo brutalism showcase nepal",
    "Rakesh Shrestha ui ux designer neo brutalism showcase kathmandu",
    // Branded — product designer
    "Rakesh Shrestha product designer neo brutalism portfolio nepal",
    "Rakesh Shrestha product designer neo brutalism portfolio kathmandu",
    "Rakesh Shrestha product designer neobrutalist portfolio nepal",
    "Rakesh Shrestha product designer brutalist ui portfolio nepal",
    "Rakesh Shrestha product designer modern brutalism portfolio nepal",
    "Rakesh Shrestha product designer bold ui portfolio nepal",
    "Rakesh Shrestha product designer experimental ui portfolio nepal",
    "Rakesh Shrestha product designer graphic heavy ui portfolio nepal",
    "Rakesh Shrestha product designer neo brutalism website nepal",
    "Rakesh Shrestha product designer neo brutalism case study nepal",
    "Rakesh Shrestha product designer neo brutalism best design nepal",
    "Rakesh Shrestha product designer neo brutalism freelance nepal",
    "Rakesh Shrestha product designer neo brutalism hire nepal",
    // Branded — user interface designer
    "Rakesh Shrestha user interface designer neo brutalism portfolio nepal",
    "Rakesh Shrestha user interface designer neobrutalist portfolio nepal",
    "Rakesh Shrestha user interface designer brutalist ui portfolio nepal",
    "Rakesh Shrestha user interface designer modern brutalism portfolio nepal",
    "Rakesh Shrestha user interface designer bold ui portfolio nepal",
    "Rakesh Shrestha user interface designer experimental ui portfolio nepal",
    "Rakesh Shrestha user interface designer graphic heavy ui portfolio nepal",
    // Branded — user experience designer
    "Rakesh Shrestha user experience designer neo brutalism portfolio nepal",
    "Rakesh Shrestha user experience designer neobrutalist portfolio nepal",
    "Rakesh Shrestha user experience designer brutalist ui portfolio nepal",
    "Rakesh Shrestha user experience designer modern brutalism portfolio nepal",
    "Rakesh Shrestha user experience designer bold ui portfolio nepal",
    "Rakesh Shrestha user experience designer experimental ui portfolio nepal",
    "Rakesh Shrestha user experience designer graphic heavy ui portfolio nepal",
    // Branded — general
    "Rakesh Shrestha neo brutalism designer nepal",
    "Rakesh Shrestha neobrutalist designer kathmandu",
    "Rakesh Shrestha brutalist ui designer nepal",
    "Rakesh Shrestha modern brutalism designer kathmandu",
    "Rakesh Shrestha bold ui designer nepal",
    "Rakesh Shrestha experimental ui designer kathmandu",
    "Rakesh Shrestha graphic heavy ui designer nepal",
    "Rakesh Shrestha hire ui ux designer nepal",
    "Rakesh Shrestha hire ui ux designer kathmandu",
    "Rakesh Shrestha freelance ui ux designer nepal",
    "Rakesh Shrestha freelance ui ux designer kathmandu",
    "Rakesh Shrestha award winning designer nepal",
    "Rakesh Shrestha award winning ui ux designer kathmandu",
    "Rakesh Shrestha best design nepal",
    "Rakesh Shrestha best design kathmandu",
    "Rakesh Shrestha professional ui ux designer nepal",
    "Rakesh Shrestha professional ui ux designer kathmandu",
    "Rakesh Shrestha showcase nepal",
    "Rakesh Shrestha showcase kathmandu",
  ],
  authors: [{ name: "Rakesh Shrestha", url: SITE_URL }],
  creator: "Rakesh Shrestha",
  publisher: "Rakesh Shrestha",

  // ── Canonical + robots ─────────────────────────────────────────────────────
  // metadataBase handles absolute URL resolution for all relative paths below.
  // The canonical is set per-page via alternates; the global fallback is the root.
  alternates: {
    canonical: SITE_URL,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // ── Open Graph ─────────────────────────────────────────────────────────────
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Rakesh Shrestha Portfolio",
    title: "Rakesh Shrestha — UI/UX Designer & Product Designer | Kathmandu, Nepal",
    description:
      "UI/UX & Product Designer in Kathmandu, Nepal. Figma expert, neobrutalist design, edtech focus. 2× hackathon runner-up. Available for freelance.",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Rakesh Shrestha — UI/UX Designer & Product Designer | Kathmandu, Nepal",
      },
    ],
  },

  // ── Twitter / X card ───────────────────────────────────────────────────────
  twitter: {
    card: "summary_large_image",
    title: "Rakesh Shrestha — UI/UX Designer & Product Designer",
    description:
      "UI/UX & Product Designer in Kathmandu, Nepal. Figma expert, neobrutalist design. 2× hackathon runner-up.",
    images: ["/opengraph-image"],
    // creator: "@yourhandle",   // add if you have a Twitter/X account
  },

  // ── Icons ──────────────────────────────────────────────────────────────────
  icons: {
    icon: [
      { url: "/favicon.png", type: "image/png" },
    ],
    apple: "/favicon.png",
  },

  // ── Verification (fill in after Search Console setup) ─────────────────────
  verification: {
    google: [
      process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION ?? "",
      process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION_2 ?? "",
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const gaId = process.env.NEXT_PUBLIC_GA_ID;
  return (
    <html lang="en">
      <body>
        {children}
        {/* Google Analytics — loads after page is interactive, doesn't block render */}
        {gaId && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${gaId}`}
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${gaId}');
              `}
            </Script>
          </>
        )}
      </body>
    </html>
  );
}
